; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = huidu_hd_wf2

[common]
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DUSE_GFX_LITE=1
lib_deps_external  =
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.0
	https://github.com/mrcodetastic/GFX_Lite
	https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA

[env:huidu_hd_wf2]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF53
board = huidu_hd_wf2
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
board_build.partitions = partitions/ota_4mb_littlefs.csv
build_flags = ${common.build_flags}
	-DWF2=1
lib_deps = ${common.lib_deps_external}
